import { Routes } from '@angular/router';
import {
  AdminCrudPageComponent,
  AdminDashboardPageComponent,
  FavoritesPageComponent,
  HomePageComponent,
  IndicatePageComponent,
  IndicationsPageComponent,
  LoginPageComponent,
  ProfessionalProfilePageComponent,
  ProfessionalsPageComponent,
  RegisterPageComponent,
  ReviewsPageComponent,
} from './pages';
import { ResidentProfilePageComponent } from './extra-pages';
import { AdminLayoutComponent, MobileLayoutComponent } from './layouts';
import { adminGuard, professionalGuard, residentGuard } from './guards/auth.guard';

export const routes: Routes = [
  { path: 'login', component: LoginPageComponent },
  { path: 'cadastro', component: RegisterPageComponent },
  { path: 'redefinir-senha', loadComponent: () => import('./reset-password-page').then((m) => m.ResetPasswordPageComponent) },
  { path: 'admin/login', loadComponent: () => import('./extra-pages').then((m) => m.AdminLoginPageComponent) },
  {
    path: 'app',
    component: MobileLayoutComponent,
    canActivate: [residentGuard],
    children: [
      { path: '', pathMatch: 'full', redirectTo: 'home' },
      { path: 'home', component: HomePageComponent },
      { path: 'buscar', component: ProfessionalsPageComponent },
      { path: 'profissionais', component: ProfessionalsPageComponent },
      { path: 'profissional/:id/comentarios', loadComponent: () => import('./comments-page').then((m) => m.CommentsPageComponent) },
      { path: 'profissional/:id', component: ProfessionalProfilePageComponent },
      { path: 'mensagens/:professionalId', loadComponent: () => import('./messages-page').then((m) => m.MessagesPageComponent) },
      { path: 'indicar', component: IndicatePageComponent },
      { path: 'avaliacoes/:id', component: ReviewsPageComponent },
      { path: 'favoritos', component: FavoritesPageComponent },
      { path: 'minhas-indicacoes', component: IndicationsPageComponent },
      { path: 'perfil', component: ResidentProfilePageComponent },
      { path: 'solicitacoes', loadComponent: () => import('./service-request-pages').then((m) => m.ServiceRequestsPageComponent) },
      { path: 'solicitacoes/nova', loadComponent: () => import('./service-request-pages').then((m) => m.ServiceRequestNewPageComponent) },
      { path: 'solicitacoes/:id', loadComponent: () => import('./service-request-pages').then((m) => m.ServiceRequestDetailsPageComponent) },
    ],
  },
  {
    path: 'profissional/perfil',
    loadComponent: () => import('./professional-account-page').then((m) => m.ProfessionalAccountPageComponent),
    canActivate: [professionalGuard],
  },
  {
    path: 'admin',
    component: AdminLayoutComponent,
    canActivate: [adminGuard],
    children: [
      { path: '', pathMatch: 'full', redirectTo: 'dashboard' },
      { path: 'dashboard', component: AdminDashboardPageComponent },
      { path: 'pendencias', loadComponent: () => import('./admin-pending-page').then((m) => m.AdminPendingPageComponent) },
      { path: 'perfil', loadComponent: () => import('./admin-profile-page').then((m) => m.AdminProfilePageComponent) },
      { path: 'condominios/novo', redirectTo: 'clientes', pathMatch: 'full' },
      { path: 'condominios/:id', redirectTo: 'clientes', pathMatch: 'full' },
      { path: 'condominios', redirectTo: 'clientes', pathMatch: 'full' },
      { path: 'moradores', redirectTo: 'clientes', pathMatch: 'full' },
      { path: 'clientes', component: AdminCrudPageComponent, data: { resource: 'residents' } },
      { path: 'usuarios', component: AdminCrudPageComponent, data: { resource: 'users' } },
      { path: 'profissionais', component: AdminCrudPageComponent, data: { resource: 'professionals' } },
      { path: 'categorias', loadComponent: () => import('./admin-category-page').then((m) => m.AdminCategoryPageComponent) },
      { path: 'avaliacoes', loadComponent: () => import('./admin-reviews-page').then((m) => m.AdminReviewsPageComponent) },
      { path: 'avaliacoes/:id', loadComponent: () => import('./admin-reviews-page').then((m) => m.AdminReviewDetailsPageComponent) },
      { path: 'indicacoes', loadComponent: () => import('./extra-pages').then((m) => m.AdminSectionPageComponent), data: { section: 'recommendations' } },
      { path: 'denuncias', loadComponent: () => import('./admin-reports-page').then((m) => m.AdminReportsPageComponent) },
      { path: 'denuncias/:id', loadComponent: () => import('./admin-report-details-page').then((m) => m.AdminReportDetailsPageComponent) },
      { path: 'configuracoes', loadComponent: () => import('./extra-pages').then((m) => m.AdminSectionPageComponent), data: { section: 'settings' } },
      { path: 'inteligencia-artificial', loadComponent: () => import('./admin-ai-page').then((m) => m.AdminAiPageComponent) },
      { path: 'relatorios', loadComponent: () => import('./extra-pages').then((m) => m.AdminSectionPageComponent), data: { section: 'reports-dashboard' } },
    ],
  },
  { path: 'home', redirectTo: 'app/home', pathMatch: 'full' },
  { path: 'profissionais', redirectTo: 'app/profissionais', pathMatch: 'full' },
  { path: 'profissionais/:id', redirectTo: 'app/profissional/:id', pathMatch: 'full' },
  { path: 'indicar', redirectTo: 'app/indicar', pathMatch: 'full' },
  { path: 'favoritos', redirectTo: 'app/favoritos', pathMatch: 'full' },
  { path: 'minhas-indicacoes', redirectTo: 'app/minhas-indicacoes', pathMatch: 'full' },
  // Carregada sob demanda: e a vitrine publica, nao faz parte do app logado.
  { path: '', pathMatch: 'full', loadComponent: () => import('./landing-page').then((m) => m.LandingPageComponent) },
  { path: '**', redirectTo: '', pathMatch: 'full' },
];
